import * as fs from "fs";
import * as path from "path";

/**
 * Exports the ABIs the frontend needs into frontend/lib/abi.ts.
 *
 *   npx hardhat run scripts/export-abi.ts
 *
 * Generated rather than hand-copied so the UI cannot drift from the deployed interface after a
 * contract change.
 */

const ROOT = path.join(__dirname, "..");

function loadAbi(contract: string, file?: string): unknown[] {
  const artifact = path.join(ROOT, "artifacts", "contracts", file ?? `${contract}.sol`, `${contract}.json`);
  const parsed = JSON.parse(fs.readFileSync(artifact, "utf-8")) as { abi: unknown[] };
  return parsed.abi;
}

/** Only the calls the UI makes, kept small and readable. */
const ERC20_ABI = [
  "function mint(address to, uint256 amount)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function decimals() view returns (uint8)",
];

const CUSDC_ABI = [
  "function wrap(address to, uint256 amount) returns (bytes32)",
  "function setOperator(address operator, uint48 until)",
  "function isOperator(address holder, address spender) view returns (bool)",
  "function confidentialBalanceOf(address account) view returns (bytes32)",
];

function main() {
  const poolAbi = loadAbi("TenurePool");

  const out = `// Generated by scripts/export-abi.ts -- do not edit by hand.
// Regenerate with: npx hardhat run scripts/export-abi.ts

export const TENURE_POOL_ABI = ${JSON.stringify(poolAbi, null, 2)} as const;

export const ERC20_ABI = ${JSON.stringify(ERC20_ABI, null, 2)} as const;

export const CUSDC_ABI = ${JSON.stringify(CUSDC_ABI, null, 2)} as const;
`;

  const dir = path.join(ROOT, "frontend", "lib");
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, "abi.ts");
  fs.writeFileSync(file, out);
  console.log(`wrote ${file} (${(out.length / 1024).toFixed(1)} KB)`);
}

main();
